package org.geysermc.hydraulic.pack.modules;

import com.google.common.base.Suppliers;
import net.kyori.adventure.text.Component;
import org.apache.commons.lang3.StringUtils;
import org.geysermc.hydraulic.Constants;
import org.geysermc.hydraulic.HydraulicImpl;
import org.geysermc.hydraulic.platform.mod.ModInfo;
import org.geysermc.hydraulic.util.PackUtil;
import org.geysermc.pack.bedrock.resource.BedrockResourcePack;
import org.geysermc.pack.bedrock.resource.Manifest;
import org.geysermc.pack.bedrock.resource.manifest.Header;
import org.geysermc.pack.bedrock.resource.manifest.Modules;
import org.geysermc.pack.converter.pipeline.*;
import org.geysermc.pack.converter.type.base.PackManifestConverter;
import org.jetbrains.annotations.Nullable;
import team.unnamed.creative.ResourcePack;
import team.unnamed.creative.metadata.pack.FormatVersion;
import team.unnamed.creative.metadata.pack.PackFormat;
import team.unnamed.creative.metadata.pack.PackMeta;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Supplier;

public class MetadataPackModule implements AssetExtractor<ModInfo>, AssetConverter<ModInfo, Manifest>, AssetCombiner<Manifest> {
    /**
     * Bedrock clients cache resource packs by (uuid, version). The pack UUID is derived from the mod
     * file, so it stays stable as long as the mod does - meaning a client that downloaded a pack once
     * keeps serving its cached copy even after Hydraulic regenerates that pack with different
     * contents. Since Hydraulic's own version determines what the conversion produces, folding it into
     * the pack version makes clients re-download whenever the conversion logic changes. Memoized
     * because deriving it hashes the whole Hydraulic mod file.
     */
    private static final Supplier<float[]> PACK_VERSION = Suppliers.memoize(() -> {
        ModInfo hydraulic = HydraulicImpl.instance().mod(Constants.MOD_ID);
        if (hydraulic == null) {
            return new float[] { 1.0f, 0.0f, 0.0f };
        }

        long bits = PackUtil.getModUUID(hydraulic.roots()).getMostSignificantBits();
        return new float[] { 1.0f, Math.floorMod(bits >> 20, 1000L), Math.floorMod(bits, 1000L) };
    });

    private final ModInfo modInfo;

    public MetadataPackModule(ModInfo modInfo) {
        this.modInfo = modInfo;
    }

    @Override
    public Collection<ModInfo> extract(ResourcePack pack, ExtractionContext context) {
        return List.of(this.modInfo);
    }

    @Override
    public @Nullable Manifest convert(ModInfo mod, ConversionContext context) throws Exception {
        Manifest manifest = PackManifestConverter.INSTANCE.convert(
                PackMeta.of(PackFormat.format(FormatVersion.of(0)), Component.text(mod.name().trim() + " " + mod.version() + " - Generated by " + Constants.MOD_NAME)),
                new ConversionContext(mod.name().trim() + " Resource Pack", context.logListener())
        );

        Header header = manifest.header();

        // Generate the pack uuid from the mod file
        String packUuid = PackUtil.getModUUID(mod.roots()).toString();
        header.uuid(packUuid);
        header.version(PACK_VERSION.get().clone());

        // Generate module uuid based on type
        for (Modules module : manifest.modules()) {
            module.uuid(UUID.nameUUIDFromBytes((module.type + packUuid).getBytes()).toString());
            module.description(mod.name().trim() + " " + StringUtils.capitalize(module.type));
            module.version(PACK_VERSION.get().clone());
        }

        return manifest;
    }

    @Override
    public void include(BedrockResourcePack pack, List<Manifest> manifests, CombineContext context) {
        pack.manifest(manifests.getFirst());

        // Copy the icon if it exists or copy the fallback icon
        try {
            if (this.modInfo.iconPath() != null) {
                pack.icon(Files.readAllBytes(this.modInfo.iconPath()));
            } else {
                try (InputStream stream = MetadataPackModule.class.getClassLoader().getResourceAsStream("unknown.png")) {
                    pack.icon(stream.readAllBytes());
                }
            }
        } catch (IOException ignored) {
        }
    }
}
